### ISSUE TITLE
Requirements: yaml

### ISSUE THREAD

**Issue by Marlysson** [kevinwuhoo/randomcolor-py#1]
To use the yaml and colormap need to download the specific library or it comes in the script?

this form, the test file too fail because are without the yaml library

``` python
import yaml
ImportError: No module named yaml
```

**Comment by kevinwuhoo** [comment]
Thanks for reporting this! I moved to using json serialization instead so that there are no external dependencies. Please fetch the latest version and let me know if you have any other problems.
