### ISSUE TITLE
Colors are too similar

### ISSUE THREAD

**Issue by davidak** [kevinwuhoo/randomcolor-py#11]
I create multiple colors independently from each other and some are very similar that way.

`'color1': rand_color.generate()[0]`
`'color2': rand_color.generate()[0]`
`'color3': rand_color.generate()[0]`

Could i create multiple colors at once and get always different colors?

I actually put the colors in a HTML template into JavaScript, so it might be better to use the JS version.

![screenshot from 2018-09-17 18-12-19](https://user-images.githubusercontent.com/91113/48201033-3c6e6200-e361-11e8-9f5f-af5d5e7672f0.png)

**Comment by hadalin** [comment]
```py
rand_color.generate(count=3)
# ['#4c52ce', '#d35098', '#b8e840']
```

**Comment by kevinwuhoo** [comment]
Sorry for the delay in response. @davidak I'm guessing you probably are past this problem by now 😅. I would do what @hadalin suggested. Feel free to reopen if this is still an issue.
