### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by erichaus** [kevinwuhoo/randomcolor-py#6]
Hello,

Running `rand_color = randomcolor.RandomColor(42)`

Gives: `FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/.virtualenvs/craft/lib/python3.4/site-packages/lib/colormap.json'`

why would a python package rely on json?

**Comment by kevinwuhoo** [comment]
Weird, I should probably add some basic testing so that this doesn't happen. It loads some data from a json file so that it's not hardcoded in the file. Maybe it's not worth the trouble though. Will fix tonight.

**Comment by erichaus** [comment]
ok word... im on py3 fwiw

**Comment by kevinwuhoo** [comment]
Just fixed this. If you update to `0.4.4.3` it should work!

``` bash
$ pip freeze
randomcolor==0.4.4.3
$ python
Python 3.5.0 (default, Sep 23 2015, 04:42:00)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import randomcolor
>>> randomcolor.RandomColor(42).generate()
['#e094be']
```

Feel free to reopen this if it's still broken for you.
