### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hadim** [kevinwuhoo/randomcolor-py#7]
I am trying to build a conda forge recipe for randomcolor (https://github.com/conda-forge/staged-recipes/pull/1845).

I need to know the license of the project ? Could you push this information on the README ?

Thank you

**Comment by hadim** [comment]
@kevinwuhoo

**Comment by hadim** [comment]
In the meantime I am assuming it's GPLv3. I will change it if you prefer another license.

**Comment by hadim** [comment]
Also the license file should be added to `MANIFEST.in` and you will have to do a github release so I can specifically build the package on that git tag.

**Comment by kevinwuhoo** [comment]
Thanks for doing this and giving me detailed instructions. I've added the MIT license, rebuilt v0.4.4.4, and uploaded to PyPI. Let me know if you have any more problems. Can close when conda-forge/staged-recipes#1845 is merged.

**Comment by hadim** [comment]
Perfect.  i'll close here when it's done.

**Comment by hadim** [comment]
`conda config --add channels conda-forge  && conda install randomcolor` now works.
